version: '3.8'
services:
  strapi:
#    container_name: "api.f6sny.com"
    image: "ghcr.io/f6sny/api.f6sny.com:latest"
    env_file:
      - stack.env
    ports:
      - "8010:80"

  nuxtjs:
#    container_name: "www.f6sny.com"
    image: "ghcr.io/f6sny/www.f6sny.com:latest"
    env_file:
      - stack.env
    ports:
      - "9022:5050"

  meilisearch:
#    container_name: "search.f6sny.com"
    image: "getmeili/meilisearch:v0.26.1"
    restart: unless-stopped
    ports:
      - "7700:7700"
    volumes:
      - /var/local/meilisearch:/data.ms
    env_file:
      - stack.env